#!/usr/bin/env python3
"""Expand each February 2026 article to 1500+ words by adding context paragraphs
to Career & Money, Love & Relationships, and Crystal of the Month sections.
Each paragraph is unique to the sign, drawn from house placement + ruler + transit logic.
"""
import json, re
from pathlib import Path

ARTICLES_DIR = Path(r"D:/Code/knowledge-base/01-AI营销/04-选品库/C端/01-疗愈水晶/04-内容生产/8.zodiac-monthly-horoscope/articles")

# Per-sign expansion paragraphs (career_extra, love_extra, crystal_extra)
# Each is genuinely differentiated by house, ruler, element, sign-specific.
EXPANSIONS = {
"aries": {
    "career_extra": "Mars in Cancer (your 4th house) all month is the secret architect here. You'll find that career progress in February doesn't come from the loud, public push your sign is famous for — it comes from private, foundational work. A contract revised at home, a client conversation held in a calm environment, or a strategy session done in writing rather than in person all favor you now. Money-wise, watch the second half of February for a referral or community-led opportunity tied to the eclipse. The Aquarius eclipse is in your 11th house of networks: someone in your circle may carry a lead, but the deal won't close until after Mercury turns direct in late March. Budget for slowness, not for sprint.",
    "love_extra": "If you're in a long-term partnership, the Saturn ingress asks you to define the next two-year arc together — not in vague terms, but in concrete ones (living situation, finances, shared goals). Aries tends to lead with action, but Saturn rewards definition first. The Feb 1 Leo full moon in your 5th house is also a play-and-romance peak: schedule a real date night, do something creative together, and let joy lead. For singles, the Saturn-Neptune conjunction in your sign can feel disorienting at first — who you are attracted to may shift noticeably. Trust the slower burn; the spark that wants commitment will outlast the spark that wants novelty.",
    "crystal_extra": "A note on choosing your Clear Quartz: a single terminated point is ideal for vision-setting (point it toward you during intention work), while a small cluster works better for environment-clearing (place it where you do your deepest thinking). Avoid heavily dyed or irradiated stones — natural Clear Quartz has a cool, neutral clarity that mirrors Saturn's structural energy. Pair it with a piece of Red Jasper or Bloodstone (your sign's traditional allies) on Feb 28 to balance Saturn's weight with Mars' fire. Cleanse it weekly under running water through February — eclipse season stirs dense energy, and your stone will work harder than usual."
},
"taurus": {
    "career_extra": "Uranus in your sign all year keeps the unconventional choice correct — a digital pivot, a niche specialization, or a rebrand that your more conservative instincts would normally resist. The Feb 17 eclipse in your 10th house is the public-facing version of this: the role or direction you've privately incubated becomes visible, sometimes before you feel ready. Trust the timing. Saturn in your 12th from Feb 13 also reveals what has been silently capping your output — a draining client, an unfinished closure, an old story about your worth. Clearing it now is the highest-leverage career work you can do this quarter. Money is steady rather than spectacular in February; the bigger shift is in *direction* and in *what you say no to*. For Taurus, the no is the work.",
    "love_extra": "If partnered, the eclipse in your 10th can make your relationship more visible — a couple's brand, a public-facing project together, or simply a phase where others project onto your partnership. Taurus tends to keep love private; this month asks for graceful visibility. Saturn in your 12th from Feb 13 also means: any unprocessed relationship history will surface now. Old griefs, unspoken resentments, or patterns you've absorbed from past partners want release. Therapy, journaling, or honest conversations with a trusted friend are well-supported. For singles, the Saturn-Neptune conjunction suggests looking beneath what looks good on paper. The person who feels grounding beneath the surface will outlast the one who only looks the part.",
    "crystal_extra": "For Taurus, the body matters — you process energy somatically, not just mentally. Black Tourmaline's weight in your hand is part of its medicine for your sign; choose a palm stone or worry stone rather than a tiny chip. Earth-sign compatibility also makes Black Tourmaline a natural pair with your traditional allies (Emerald, Rose Quartz, or Pyrite). On Feb 1 (Leo full moon, your 4th house), place the stone at the center of your home for 24 hours to absorb any family-system static before the Saturn ingress. From Feb 26 onward, hold it for three breaths before opening email — Mercury Rx in your 11th house of networks can stir delayed-message anxiety, and your nervous system benefits from the pause."
},
"gemini": {
    "career_extra": "Mercury in Capricorn (your 8th house) through mid-February brings a serious, intimate tone to contracts and shared resources — a research project, a financial negotiation, or a deep-dive collaboration suits you better than surface-level networking. When Mercury moves into Aquarius (your 9th house) close to the eclipse, your scope expands: this is when a publishing, teaching, or international opportunity can crystallize. Then Mercury turns retrograde on Feb 26 in Pisces (your 10th house), which means the public-facing version of your work goes into review mode — revise your bio, redo your narrative, revisit your title. Do not launch the new platform or sign the big contract this month. The Gemini instinct to scatter across five channels backfires now; Saturn in your 11th rewards depth in one community.",
    "love_extra": "For Gemini, Venus in Capricorn (your 8th house) for most of February brings intensity to intimate bonds — a partner's finances, a depth conversation, or a healing arc surfaces. This isn't light dating weather; it's about real vulnerability. The Feb 1 Leo full moon in your 3rd house supports a clear conversation with a partner, sibling, or close friend — write down what you want to say first so you don't edit yourself into vagueness. For singles, the Feb 17 eclipse in your 9th house can introduce someone with a markedly different worldview — different field, different country, different spiritual path. Saturn's presence in your 11th says: choose the community that lets you be yourself, not the one that requires you to perform. Mercury Rx from Feb 26 may bring back a past partner or pattern — proceed with discernment, not nostalgia.",
    "crystal_extra": "Gemini benefits from working with Smoky Quartz in motion rather than in stillness — a worry stone carried in your pocket, or a piece you hold while walking, matches your air-sign need for movement. Avoid placing it near your bed for sleep; its grounding weight can feel heavy for a sign that processes through dreams. On Feb 17 (your 9th-house eclipse), write your three-sentence belief statement with the stone in your non-dominant hand — the receiving hand, where input becomes integration. From Feb 26 (Mercury Rx), keep it beside your keyboard when email starts looping. For Gemini, the trap during Mercury Rx is the *refreshing-feeds loop*; Smoky Quartz's gentle gravity pulls attention back to the body and out of the screen."
},
"cancer": {
    "career_extra": "Cancer, your career in February 2026 has two distinct speeds. The first half (through the Feb 1 Leo full moon) is about closing a money or self-worth storyline — a contract finalized, a pricing decision made, a personal boundary with a client or employer reinforced. The second half is the long Saturn-in-your-10th arc beginning: this is the start of building real authority in your field, the kind rooted in mastery and endurance rather than office politics. Saturn hasn't been in your 10th since 1996–1999, so this is genuinely new territory. The 8th-house solar eclipse on Feb 17 can revise a shared financial arrangement — a debt, an investment, a partnership split. Don't finalize eclipse week; review and refine. The Mars transit through Cancer (your 1st house) all month gives you more personal energy than usual — channel it into one project, not five.",
    "love_extra": "Venus in Capricorn (your 7th house of partnership) for most of February makes love serious and committed for Cancer — a long-term partnership either deepens or faces honest reckoning. The 8th-house solar eclipse on Feb 17 is the more dramatic story: it rewrites intimacy, shared resources, and psychological merging. An existing bond either deepens into real commitment or releases. Single? The eclipse window (Feb 14-20) can introduce someone who challenges your usual patterns — Saturn's involvement says choose substance over the comfort of familiarity. If you're in an established partnership, this is the month to talk about money, sex, secrets, and shared resources — topics Cancer tends to handle indirectly. Directness is the work now. For more on stones traditionally connected with emotional healing, browse [/crystals-for-anxiety/](/crystals-for-anxiety/).",
    "crystal_extra": "Cancer is ruled by the Moon, which means your stone needs regular moonlight cleansing — Amethyst is no exception. Place it in direct moonlight on the nights of Feb 1 (Leo full moon) and Feb 16 (eve of your 8th-house eclipse) to keep its clarity high. As a water sign, you may also benefit from a small bowl of water beside the stone; Amethyst and water are traditional companions, and the visual of still water supports your emotional processing. On Feb 17, hold the stone against your heart center while you write your release list. From Feb 26 (Mercury Rx in your 9th), keep it near your reading chair — belief-review work is well-supported by Amethyst's traditional calming association."
},
"leo": {
    "career_extra": "Leo, with Saturn entering your 9th house on Feb 13, your career tilts toward teaching, publishing, international work, or thought leadership for the next 2.5 years. This is the Leo-flavored authority that scales — your voice reaching a wider audience through courses, books, broadcasts, or long-form work. The Feb 1 full moon in your sign already hands you a recognition moment: a launch, a leadership role, a personal rebrand peaks. Move into it. Then the Feb 17 eclipse in your 7th house can shift a business partnership — a collaborator may enter, exit, or renegotiate. Mercury Rx from Feb 26 in your 8th house brings a shared-resources review (a partner's income, an investment, a debt). Money is steady rather than dramatic in February; the bigger shift is in *direction* and *who you build with*.",
    "love_extra": "This is the love-story month of your year — possibly your decade. The Feb 17 solar eclipse in your 7th house is the most partnership-defining transit of 2026 for Leo. Saturn entering your 9th simultaneously means: your partner (current or future) needs to match your worldview, not just your aesthetic. Single? An introduction is possible eclipse week, but Saturn's involvement says: this one wants substance, not just performance. Partnered? The relationship either deepens into real commitment or surfaces the gap. The Feb 1 Leo full moon in your sign is a confidence peak — schedule a meaningful date night, share something vulnerable, and let your radiance lead. Venus in Capricorn (your 6th house) for most of February brings a practical, service-oriented tone to love — small acts of daily care matter more than grand gestures this month.",
    "crystal_extra": "Leo benefits from working with Clear Quartz as an amplifier alongside your sign's traditional stones (Sunstone, Citrine, Tiger's Eye). On Feb 1 (your full moon), place Clear Quartz between a Sunstone and a Citrine to form a solar triangle — a traditional Leo arrangement for confidence and radiance. Avoid heavily irradiated or treated Clear Quartz; the natural cool clarity of the stone is the point. As a fire sign ruled by the Sun, you may find Clear Quartz most alive in direct sunlight — five minutes of solar charging each morning through February matches your solar nature. On Feb 17 (the 7th-house eclipse), hold the stone while you write the qualities of your ideal partner. Saturn in your 9th means: include worldview, not just chemistry, on the list."
},
"virgo": {
    "career_extra": "Virgo, the Feb 17 solar eclipse in your 6th house is a rare direct address to your home territory — daily work, health routines, and service. A daily system, a role, or a health pattern is being rewritten. As a Mercury-ruled earth sign, you instinctively know how to refine a system; the eclipse asks you to redesign rather than optimize. Saturn entering your 8th from Feb 13 begins a 2.5-year arc of getting serious about shared money, debts, investments, and psychological depth — themes you tend to manage rather than examine. The Feb 1 Leo full moon in your 12th asks you to complete a closure before reopening the system. Money is steady in February; Mercury Rx in your 7th from Feb 26 brings a partnership-contract review — revisit agreements, don't sign new ones.",
    "love_extra": "Mercury turning retrograde in your 7th house of partnership on Feb 26 is the love story of February — but it's a review, not a launch. Expect to revisit a conversation, an agreement, or a past partner. Saturn's arrival in your 8th from Feb 13 begins a 2.5-year arc of deepening intimacy: shared resources, vulnerability, sexual dynamics, and psychological honesty become the work. Virgo tends to serve rather than surrender; Saturn in the 8th asks you to receive. The Feb 1 Leo full moon in your 12th supports releasing a hidden emotional pattern before it surfaces in partnership. Single? Mercury Rx in your 7th can return an ex or past pattern — proceed with discernment, not nostalgia. The right partner now wants your real self, not your capable self.",
    "crystal_extra": "Virgo benefits from working with Black Tourmaline in structured ways — a daily ritual at the same time each morning matches your sign's need for rhythm. Place a piece at your workstation for the entire month of February; the 6th-house eclipse activates your work environment, and the stone's traditional protective quality supports energetic hygiene. As an earth sign, you may prefer a smooth tumbled stone over a raw crystal; both work, but the tumbled form supports Virgo's preference for refinement. On Feb 17 (your 6th-house eclipse), write your *what works / what drains* lists with the stone nearby. From Feb 26 (Mercury Rx), hold it before opening email — the three-breath pause is real medicine for a Mercury-ruled nervous system under Mercury Rx."
},
"libra": {
    "career_extra": "Libra, the Feb 17 eclipse in your 5th house is the creative-rebirth eclipse of your year — a body of work you've privately incubated is being written into your next chapter. Saturn entering your 7th from Feb 13 simultaneously makes partnerships (business and romantic) the serious work for 2.5 years. Collaborations, contracts, and committed alliances get heavier and more defining. Venus in Capricorn (your 4th house) for most of the month supports a home-based income or family financial decision — acozy office pivot, a family business, or a real-estate move benefits you now. Mercury Rx in your 6th from Feb 26 brings daily-routine and health-benefit review. Money is steady rather than spectacular in February; the bigger shift is in *who you build with* and *what you create*. For stones traditionally associated with creative flow and abundance, see [/crystals-for-wealth/](/crystals-for-wealth/).",
    "love_extra": "This is the most partnership-defining month of your decade. Saturn hasn't been in your 7th house since 1996–1999; its arrival on Feb 13-14 opens a 2.5-year arc where partnerships get serious — for better or for closure. The Feb 17 eclipse in your 5th house simultaneously rewrites romance, creativity, and joy. Single? A significant romance is possible eclipse week, but Saturn's involvement says this one wants substance. Partnered? The relationship either deepens into real commitment or faces the gap. Venus in your 4th house supports domestic love — cozy nights, family expansion, a home decision together. Libra's instinct is to harmonize; Saturn's instruction is to commit. The difference matters now.",
    "crystal_extra": "Libra benefits from working with Smoky Quartz in pairs — two tumbled stones, one in each pocket, support your Venus-ruled need for balance. As an air sign, you process energy through relationship; the Smoky Quartz's gentle gravity pulls you back to your own center when you've been over-absorbing a partner's emotional state. On Feb 17 (your 5th-house eclipse), hold a single piece in your receiving hand while you write the name of your next creative project. From Feb 13 (Saturn ingress), keep a piece on your nightstand for 7th-house boundary work during sleep. Pair it with Rose Quartz — your traditional ally — for a balanced Libra toolkit through the Saturn-in-Aries years ahead."
},
"scorpio": {
    "career_extra": "Scorpio, the Feb 1 Leo full moon in your 10th house is the visibility peak of your first quarter — a role, a launch, or a public recognition moment. Saturn entering your 6th from Feb 13 then begins a 2.5-year arc of getting serious about daily craft and health. As a Mars-and-Pluto-ruled water sign, your power comes from depth and endurance; Saturn in the 6th rewards consistent, sustainable practice over heroic sprints. The 4th-house eclipse on Feb 17 can shift your living situation, family structure, or sense of inner foundation — work and home may reorganize together. Mars, your traditional ruler, in Cancer (your 9th house) all month supports expansive career moves through teaching, publishing, or international work. Mercury Rx in your 5th from Feb 26 brings creative review.",
    "love_extra": "Mars in your 9th house all month supports expansive, worldview-deepening love — a partner who teaches you something, or romance with someone from a different background, country, or faith. The Feb 1 Leo full moon in your 10th can make a relationship more visible (or make you attractive at work). The 4th-house eclipse on Feb 17 is the private love story: family dynamics, a home decision with a partner, or a release of inherited relational patterns you've carried since childhood. Scorpio tends to merge; Saturn in your 6th says: build the daily structure that lets intimacy thrive without collapsing your separate self. Single? Someone steady, who shows up daily, out-charms the dramatic. For more on stones traditionally connected with depth and protection, browse [/crystals-for-anxiety/](/crystals-for-anxiety/).",
    "crystal_extra": "Scorpio benefits from working with Amethyst in private, intentional spaces rather than public ones — your sign processes energy through depth, and Amethyst supports that inner work. A bedroom arrangement is ideal: place a piece on your nightstand for the entire month, and especially during the Feb 17 4th-house eclipse, when family-system patterns may surface in dreams. As a water sign co-ruled by Mars and Pluto, you can also pair Amethyst with Malachite or Obsidian (your sign's traditional allies) for transformation work. On Feb 17, hold the stone against your heart while you walk through your home. Cleanse it weekly in moonlight — eclipse season stirs dense energy, and a Scorpio's stone works harder than most."
},
"sagittarius": {
    "career_extra": "Sagittarius, the Feb 17 3rd-house eclipse rewrites your communication infrastructure — writing, teaching, podcasting, social platforms, sibling relationships. As a Jupiter-ruled fire sign, your voice is your career engine, and this eclipse clarifies the message. Saturn entering your 5th from Feb 13 begins a 2.5-year arc where creative work gets serious: a long-form project, a craft discipline, a romantic pattern you commit to breaking or building. The Feb 1 Leo full moon in your 9th already supports a publishing, teaching, or international moment. Jupiter, your ruling planet, is still in Cancer (your 8th house), holding depth work in the background — research, a major investigation, or psychological transformation underpins your public work. Money is steady, with income potential from writing or teaching channels.",
    "love_extra": "Saturn entering your 5th house for 2.5 years is the love story of your decade — your 5th rules romance, joy, creative-romantic energy, and play. Single? Sagittarius' typical freedom-loving pattern gets serious: a romance now wants commitment, not just chemistry. Saturn rewards the willingness to stay and build rather than to chase the next adventure. Partnered? The relationship either deepens into true playmate status or faces the gap between freedom and intimacy. The Feb 1 Leo full moon in your 9th supports dating across worldviews — someone from a different country, faith, or field of knowledge. The 3rd-house eclipse on Feb 17 may also introduce someone through writing, local community, or a sibling network. Sagittarius tends to idealize; Saturn says: see the real person, not the projection.",
    "crystal_extra": "Sagittarius benefits from working with Clear Quartz in motion — a piece you carry on walks, hikes, or travel matches your fire-sign need for movement. The traditional Jupiter-ruled stones (Lapis Lazuli, Citrine, Turquoise) pair naturally with Clear Quartz for your sign; a three-stone arrangement on Feb 28 (six-planet alignment) supports the Sagittarian gift for synthesis. On Feb 17 (your 3rd-house eclipse), hold the stone against your throat while you write your one-sentence message. As a fire sign, you can charge Clear Quartz in direct sunlight for short periods (5-10 minutes) — longer than 30 minutes may feel over-stimulating for your already-expansive nature. Cleanse it weekly under running water through February.",
    "crystal_extra_extra": ""
},
"capricorn": {
    "career_extra": "Capricorn, the Feb 17 eclipse in your 2nd house is the money-eclipse of your year — an income stream, a pricing decision, or a self-worth conversation is being rewritten. As a Saturn-ruled earth sign, you understand structure; now Saturn's move to your 4th means career stability depends on home stability for the next 2.5 years. A move, a family decision, or a foundation-level reset ripples directly into your work. The Feb 1 Leo full moon in your 8th already brought shared resources to a head — a partner's income, an investment, or a debt. Venus in your 1st house for most of the month supports a personal rebrand and presence. Mercury Rx in your 3rd from Feb 26 brings writing and communication review. For long-term wealth-building tools and stones traditionally associated with grounded abundance, see [/crystals-for-wealth/](/crystals-for-wealth/).",
    "love_extra": "The Feb 1 Leo full moon in your 8th house brings intimacy themes to a peak — a partner's vulnerability, a sexual dynamic, a shared secret, or a financial merger. Saturn entering your 4th from Feb 13 begins a 2.5-year arc where family and home define your love story: a partner may move in, a parent may need care, or you may finally settle in a way Capricorn has delayed for years. Venus in your sign for most of February makes you magnetic — a personal rebrand ripples into romance. Single? Saturn in your 4th says: someone who feels like home, not someone who feels like an adventure. Capricorn tends to lead with ambition; Saturn now asks you to lead with rootedness. The right partner wants your foundation, not your resume.",
    "crystal_extra": "Capricorn benefits from working with Black Tourmaline in structural arrangements — a grid at the four corners of your home, or a stone placed at your front door, matches your Saturn-ruled need for architecture. As an earth sign, you may prefer a raw or natural piece over a polished one; both work, but the raw form resonates with Capricorn's respect for what is unpolished and real. On Feb 13-14 (Saturn ingress), place the stone at your home's threshold and let it stay for the full 2.5-year cycle. Pair it with Garnet — your sign's traditional ally — for added root support. From Feb 26 (Mercury Rx in your 3rd), keep a small piece beside your keyboard to support clear writing under communication review."
},
"aquarius": {
    "career_extra": "Aquarius, Saturn entering your 3rd house from Feb 13 begins a 2.5-year arc where your voice becomes the work — writing, teaching, broadcasting, and sibling-like collaborations get serious and defining. As Saturn-ruled Aquarius, this is your home turf; long-form commitment to one message will define your next chapter. The Feb 17 1st-house eclipse simultaneously rewrites your public identity: how you present, what you represent, what you stand for. Venus in Capricorn (your 12th house) for most of the month supports behind-the-scenes work — research, healing, or private projects incubate well now. Mercury Rx in your 2nd from Feb 26 brings income review: revise pricing and offerings, but don't sign new financial commitments. Money is steady; the bigger shift is in *identity* and *message*.",
    "love_extra": "The Feb 1 Leo full moon in your 7th house brings a partnership storyline to its peak — a romance, a business partnership, or a significant commitment. Then your 1st-house eclipse on Feb 17 rewrites *you*, which inevitably rewrites who belongs beside you. Saturn in your 3rd from Feb 13 makes communication the work of love for the next 2.5 years: how you talk, how you listen, how you write to those you care about. Aquarius tends to idealize partnership from a distance; Saturn says: build the daily conversational muscle. Single? The eclipse window (Feb 14-20) can introduce someone who reflects your new identity — but Saturn says substance over spark. For more on stones traditionally connected with grounded love, see [/crystals-for-anxiety/](/crystals-for-anxiety/).",
    "crystal_extra": "Aquarius benefits from working with Smoky Quartz in intentional, structured arrangements rather than casual ones — your Saturn-ruled nature responds well to ritual. A piece on your writing desk for the full month of February supports the 3rd-house Saturn work (communication as discipline). On Feb 17 (your 1st-house eclipse), hold the stone against your heart center while you write your three-line identity statement. As an air sign, you may also benefit from placing it near technology — Smoky Quartz's traditional association with grounding excess energy makes it a useful companion for screen-heavy Aquarian work. Pair it with Amethyst — your sign's modern ruler's stone — for a balanced Aquarian toolkit through the Saturn-in-Aries years."
},
"pisces": {
    "career_extra": "Pisces, Saturn entering your 2nd house from Feb 13 begins a 2.5-year arc of getting serious about money, income, and self-worth — themes Pisces often spiritualizes rather than structures. Saturn's arrival says: the work is to make your value tangible. The Feb 17 12th-house eclipse supports completing a hidden chapter — a project you've been quietly finishing, a pattern you've been working to release, a creative work that needs final revisions before it sees light. The Feb 1 Leo full moon in your 6th already brought a daily-work rhythm to a peak. Mars in Cancer (your 5th house) all month supports creative momentum and romantic energy. Mercury Rx in your sign from Feb 26 slows communication and identity review. Money: review rather than launch this month; the bigger work is finishing and clearing.",
    "love_extra": "The Feb 1 Leo full moon in your 6th house supports warm, everyday love — cozy routines, shared health practices, acts of service. Saturn in your 2nd from Feb 13 begins a 2.5-year arc where self-worth shapes your love story: your value (or undervaluing) ripples into every relationship. Pisces tends to merge; Saturn says: know your worth first, then merge consciously. The 12th-house eclipse on Feb 17 is private and introspective — closure of an old pattern, healing of a hidden wound, or a dream that clarifies a relationship truth. Single? Rest now; your season begins in March, and the right introduction comes when you're not chasing. For more on stones traditionally connected with emotional healing and self-worth, browse [/crystals-for-anxiety/](/crystals-for-anxiety/).",
    "crystal_extra": "Pisces benefits from working with Amethyst in water-adjacent ways — a piece beside your bath, on your nightstand, or near a glass of water you sip through the day matches your water-sign nature. As the sign co-ruled by Neptune (modern) and Jupiter (traditional), you are the most porous, dream-sensitive sign of the zodiac; Amethyst's traditional association with calm and clarity supports your boundary work. On Feb 17 (your 12th-house eclipse), place the stone under your pillow with the question: *what am I completing?* From Feb 26 (Mercury Rx in your sign), carry a small piece in your pocket — your ruling region slows, and the stone's traditional calming quality supports clear communication under pressure. Pair it with Moonstone or Aquamarine — your sign's traditional allies — for the full Pisces toolkit."
}
}

def expand_article(sign):
    fp = ARTICLES_DIR / f"{sign}-february-2026.json"
    with open(fp, encoding="utf-8") as f:
        data = json.load(f)
    content = data["content"]
    exp = EXPANSIONS[sign]

    # Insert career_extra after the Career section's first paragraph block
    # Find the end of Career & Money section (next ## heading)
    career_match = re.search(r'(## Career & Money\n.+?)(?=\n## )', content, re.DOTALL)
    if career_match:
        career_section = career_match.group(1)
        new_career = career_section + "\n\n" + exp["career_extra"]
        content = content.replace(career_section, new_career)

    # Insert love_extra into Love section
    love_match = re.search(r'(## Love & Relationships\n.+?)(?=\n## )', content, re.DOTALL)
    if love_match:
        love_section = love_match.group(1)
        new_love = love_section + "\n\n" + exp["love_extra"]
        content = content.replace(love_section, new_love)

    # Insert crystal_extra into Crystal section
    crystal_match = re.search(r'(## Crystal of the Month\n.+?)(?=\n## )', content, re.DOTALL)
    if crystal_match:
        crystal_section = crystal_match.group(1)
        new_crystal = crystal_section + "\n\n" + exp["crystal_extra"]
        content = content.replace(crystal_section, new_crystal)

    data["content"] = content
    with open(fp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    word_count = len(content.split())
    print(f"{sign:<14} expanded -> {word_count} words")
    return word_count

counts = []
for sign in EXPANSIONS:
    c = expand_article(sign)
    counts.append(c)

print(f"\nMin: {min(counts)}, Max: {max(counts)}, Avg: {sum(counts)//len(counts)}")
print(f"All >= 1500: {all(c >= 1500 for c in counts)}")
