import json, re, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
d = json.load(open(r'D:/Code/knowledge-base/01-AI营销/04-选品库/C端/01-疗愈水晶/04-内容生产/5.crystal-combinations/articles/moonstone-and-opal.json', encoding='utf-8'))
c = d['content']
print('VALID_JSON')
print('tier', d['tier'], 'score', d['score'])
m2 = re.search(r'About Moonstone</h2>(.*?)<h2>About Opal', c, re.S).group(1)
m3 = re.search(r'About Opal</h2>(.*?)<h2>Can You Wear', c, re.S).group(1)
m4 = re.search(r'Can You Wear Moonstone and Opal Together\?</h2>(.*?)<h2>Benefits of Moonstone', c, re.S).group(1)
wc = lambda t: len(re.sub(r'<[^>]+>', ' ', t).split())
print('M2', wc(m2))
print('M3', wc(m3))
print('M4', wc(m4))
m5 = re.search(r'Benefits of Moonstone \+ Opal</h2>(.*?)<h2>How to Use Moonstone', c, re.S).group(1)
h3 = re.findall(r'<h3>(.*?)</h3>', m5)
print('M5count', len(h3))
for h in h3:
    print(' -', re.sub(r'<[^>]+>', '', h))
low = c.lower()
print('forbidden anxiety', low.count('anxiety'))
print('forbidden pillow', low.count('under the pillow'))
print('forbidden scientifically', low.count('scientifically'))
print('forbidden insomnia', low.count('insomnia'))
print('SiO2_upper', 'SiO₂' in c)
print('bad_sio', 'sio₂' in low)
print('m5ben', len(d['modules']['m5_agent']['benefits']))
print('m6long', d['modules']['m6_agent']['longtail'])
print('m6uses', d['modules']['m6_agent']['uses'])
