"""Idempotently upload a T17 site-import media manifest to WordPress Media.

The manifest is generated by build_linganshi_site_import.py. The uploader is
write-protected by --execute and an exact host confirmation, preserves prior
successful rows, and uses a browser-identifying UA required by the site's
Cloudflare rule.
"""
from __future__ import annotations

import argparse
import base64
import csv
import json
import mimetypes
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "data" / "v3" / "site-imports" / "linganshi-media-manifest.csv"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0 Safari/537.36"


def load_env() -> dict[str, str]:
    values = dict(os.environ)
    for path in (Path.home() / ".env", Path(r"D:\Code\.env")):
        if not path.is_file():
            continue
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            if key.strip() in {"WP_SITE", "WP_USER", "WP_APP_PASSWORD"}:
                values[key.strip()] = value.strip()
    return values


def request_json(url: str, auth: str, method: str = "GET", body: bytes | None = None, headers: dict[str, str] | None = None) -> tuple[int, object]:
    request_headers = {
        "Authorization": auth,
        "Accept": "application/json",
        "User-Agent": UA,
        "Referer": "https://goearthward.com/wp-admin/",
    }
    request_headers.update(headers or {})
    request = urllib.request.Request(url, data=body, headers=request_headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            payload = response.read()
            return response.status, json.loads(payload.decode("utf-8")) if payload else {}
    except urllib.error.HTTPError as error:
        payload = error.read().decode("utf-8", "replace")
        raise RuntimeError(f"HTTP {error.code} for {url}: {payload[:500]}") from error


def write_manifest(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    if ROOT not in path.parents:
        raise RuntimeError(f"Manifest escaped project root: {path}")
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--execute", action="store_true", help="Perform WordPress media writes.")
    parser.add_argument("--confirm-site", default="", help="Must exactly equal the WordPress host before writing.")
    parser.add_argument("--limit", type=int, default=0, help="Maximum pending entries to process; zero means all.")
    args = parser.parse_args()

    if not args.manifest.is_file() or ROOT not in args.manifest.parents:
        raise FileNotFoundError(args.manifest)
    with args.manifest.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        fields = list(reader.fieldnames or [])
        rows = list(reader)
    required = {"material_key", "source_product_name_zh", "source_image_path", "upload_filename", "wordpress_attachment_id", "wordpress_media_url", "upload_status"}
    if not rows or set(fields) != required:
        raise RuntimeError("Media manifest does not match the T17 operational contract")
    missing = [row["source_image_path"] for row in rows if not Path(row["source_image_path"]).is_file()]
    if missing:
        raise RuntimeError(f"Media manifest has {len(missing)} missing local files")

    env = load_env()
    site = env.get("WP_SITE", "").strip().rstrip("/")
    user = env.get("WP_USER", "").strip()
    password = env.get("WP_APP_PASSWORD", "").strip()
    if not site or not user or not password:
        raise RuntimeError("WP_SITE, WP_USER and WP_APP_PASSWORD are required")
    base_url = site if "://" in site else "https://" + site
    host = urllib.parse.urlparse(base_url).netloc
    pending = [row for row in rows if not row["wordpress_media_url"].strip()]
    print(f"site={host} manifest_rows={len(rows)} pending={len(pending)} execute={args.execute}")
    if not args.execute:
        print("DRY RUN: no WordPress requests or local manifest writes were performed")
        return 0
    if args.confirm_site.strip().lower() != host.lower():
        raise RuntimeError("Refusing WordPress writes: --confirm-site must equal the configured host")

    auth = "Basic " + base64.b64encode(f"{user}:{password}".encode("utf-8")).decode("ascii")
    limit = args.limit if args.limit > 0 else len(pending)
    uploaded = reused = 0
    for row in pending[:limit]:
        key = row["material_key"]
        query = urllib.parse.urlencode({"slug": key, "context": "edit", "per_page": 1})
        _, existing = request_json(f"{base_url}/wp-json/wp/v2/media?{query}", auth)
        if isinstance(existing, list) and existing:
            media = existing[0]
            status = "reused-existing-media"
            reused += 1
        else:
            source = Path(row["source_image_path"])
            status_code, media = request_json(
                f"{base_url}/wp-json/wp/v2/media",
                auth,
                method="POST",
                body=source.read_bytes(),
                headers={
                    "Content-Type": mimetypes.guess_type(source.name)[0] or "image/webp",
                    "Content-Disposition": f'attachment; filename="{row["upload_filename"]}"',
                },
            )
            if status_code not in {200, 201} or not isinstance(media, dict):
                raise RuntimeError(f"Unexpected media response for {key}: {status_code}")
            uploaded += 1
            status = "uploaded-t17-catalog-media"
            metadata = json.dumps({"title": row["source_product_name_zh"], "alt_text": row["source_product_name_zh"]}, ensure_ascii=False).encode("utf-8")
            request_json(f"{base_url}/wp-json/wp/v2/media/{media['id']}", auth, method="POST", body=metadata, headers={"Content-Type": "application/json; charset=utf-8"})
        row["wordpress_attachment_id"] = str(media.get("id", ""))
        row["wordpress_media_url"] = str(media.get("source_url", ""))
        row["upload_status"] = status
        write_manifest(args.manifest, rows, fields)
        print(f"{uploaded + reused}/{limit} {status} {key} attachment={row['wordpress_attachment_id']}")
        time.sleep(0.15)
    print(f"PASS uploaded={uploaded} reused={reused} manifest={args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
